FROM chromedp/headless-shell

RUN apt-get update -y \
  && apt-get install -y --no-install-recommends fonts-noto \
  && apt-get install -y --no-install-recommends fonts-noto-cjk \
  && rm -rf /var/lib/apt/lists/*
